# Generated by Django 3.1.7 on 2021-05-28 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0002_auto_20210527_1930'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id_availability', models.AutoField(primary_key=True, serialize=False)),
                ('day_of_week', models.IntegerField(default=1)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('id_tutor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='availabilities', to='tutor.tutor')),
            ],
        ),
    ]
