# Generated by Django 3.1.7 on 2021-05-28 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0004_auto_20210528_0005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hour',
            fields=[
                ('id_hour', models.AutoField(primary_key=True, serialize=False)),
                ('start', models.TimeField(default='00:00:00')),
                ('end', models.TimeField(default='01:00:00')),
            ],
        ),
    ]
