# Generated by Django 3.1.7 on 2021-05-28 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0005_hour'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hour',
            old_name='end',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='hour',
            old_name='start',
            new_name='start_time',
        ),
    ]
