# Generated by Django 3.1.7 on 2021-05-28 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0002_auto_20210527_1930'),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teaches',
            fields=[
                ('id_teach', models.AutoField(primary_key=True, serialize=False)),
                ('id_course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teaches', to='course.course')),
                ('id_tutor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scores', to='tutor.tutor')),
            ],
        ),
    ]
