# Generated by Django 3.1.7 on 2021-05-27 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id_score', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.IntegerField(default=12341234)),
                ('comment', models.CharField(max_length=300)),
                ('id_appointment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scores', to='appointment.appointment')),
            ],
        ),
    ]
